export const mockTemplate = {
  name: "first-template",
  org: "sandbox",
  tenant: "demoassure",
  attributes: [
    {
      version: "0.1",
      event: "Quote",
      metadata: "email",
      limit: 1,
      metadataType: "string",
      displayName: "Email",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "Make",
      metadataType: "string",
      limit: 1,
      displayName: "Make",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadataType: "string",
      metadata: "Model",
      limit: 1,
      displayName: "Model",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "License Plate",
      metadataType: "string",
      limit: 1,
      displayName: "License Plate",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      metadataType: "string",
      event: "Quote",
      metadata: "ltv",
      limit: 1,
      displayName: "LTV",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "firstName",
      limit: 1,
      metadataType: "string",
      displayName: "First Name",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "zipCode",
      limit: 1,
      displayName: "Zip Code",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      metadataType: "string",
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "street",
      limit: 1,
      displayName: "Street",
      lookbackDurationType: "days",
      metadataType: "string",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadata: "apt",
      metadataType: "string",
      limit: 1,
      displayName: "Apt",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadataType: "string",
      metadata: "city",
      limit: 1,
      displayName: "City",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
    {
      version: "0.1",
      event: "Quote",
      metadataType: "string",
      metadata: "lastName",
      limit: 1,
      displayName: "Last Name",
      lookbackDurationType: "days",
      lookbackPeriod: 50,
      aggregationMode: "Value",
      verbose: false,
    },
  ],
};

export const mockAction = {
  name: "first",
  version: "1.0",
  active: true,
  org: "acmecorp",
  namespace: "sandbox",
  templateId: "xxx",
  rules: {
    args: ["Quote,ltv,value EQ 1000", "Quote,zipcode,value EQ 560021"],
    logic: "AND",
  },
  actionsTriggers: [
    {
      type: "WebexWalkin",
      agentId: "123",
      nickName: "Nick",
      welcomeMessage: "Welcome!",
    },
  ],
};
